### ISSUE TITLE
Oblivious Targets and certificates with referring IP addresses.

### ISSUE THREAD

**Issue by jaymoreau** [tfpauly/draft-ohai-svcb-config#28]
In section 4.2.1, it suggests using the TLS certificate check described in [DDR], but the DDR certificate check requires listing valid referring IP addresses and then checking those. If the client is not connecting to the oblivious target directly, referring IP addresses would not be useful. The draft should have something explicit here around what validation can take place when clients connect through the Oblivious Proxy. Even if one were to connect directly to Oblivious Target for fetching keys and/or well known proxies and then connect through the proxy, there doesn't appear to be a way to validate IPs in a SAN for the Oblivious Target connection with what is described. The Oblivious Proxy should validate the TLS certificate hostname, and Oblivious Proxies can maintain trusted Oblivious Target hostname lists. Can we add language to loosen this requirement?

**Comment by tireddy2** [comment]
In this case, the client must use a transport proxy to check if the oblivious target certificate includes the IP address or not. It cannot use a HTTPS proxy. 

I don't see a need to relax the verified discovery defined in Section 4.2 of DDR otherwise the client will end-up doing opportunistic discovery.
